variables:
  GIT_SUBMODULE_STRATEGY: normal

.core-defs:
  variables:
    CORENAME: citra
    EXTRA_PATH: src/citra_libretro
    CORE_ARGS: -DENABLE_LIBRETRO=1 -DENABLE_SDL2=0 -DENABLE_QT=0 -DENABLE_WEB_SERVICE=0

.core-linux-defs:
  extends: .core-defs
  variables:
    CORE_ARGS: -DENABLE_LIBRETRO=1 -DLIBRETRO_STATIC=1 -DENABLE_SDL2=0 -DENABLE_QT=0 -DENABLE_WEB_SERVICE=0

include:
  - template: Jobs/Code-Quality.gitlab-ci.yml
  - project: 'libretro-infrastructure/ci-templates'
    file: '/linux-cmake.yml'

stages:
  - build-prepare
  - build-shared
  - test

#Desktop
libretro-build-linux-x86_64:
  extends:
    - .libretro-linux-cmake-x86_64
    - .core-linux-defs
